### ISSUE TITLE
stereo view

### ISSUE THREAD

**Issue by davecotter** [ndavd/ncube#6]
you're showing a 2d shadow of a 3d shadow of a 4d object.
if you view in stereo, you get rid of one of those layers: you'll see a 3d shadow of a 4d object

at least do parallel / cross eyed 2-up!!

**Comment by ndavd** [comment]
Using orthographic projection the results look promising.

However, I try to be strict regarding backwards compatibility of data files and will also need to rewrite the way "zooming" works. I'll need to take some thought on what's the best way to approach this.

Will be supporting both types of camera projections: perspective and orthographic.

Here are some previews in the meantime:
<div>
<img width="300" src="https://github.com/ndavd/ncube/assets/74260683/94382a7b-e6c4-46c0-af11-d6c70a30ff57" />
<img width="300" src="https://github.com/ndavd/ncube/assets/74260683/1e28d635-4009-4286-9dfc-0737b099ed78" />
</div>

**Comment by davecotter** [comment]
can you add a cross-your-eyes side by side preview? :D

**Comment by ndavd** [comment]
Not sure what that is, can you elaborate?
